# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("*{background: black; color: white}\n"
"QPushButton{background: rgb(50,50,50);}\n"
"QPushButton:disabled{ background: #6C6C6C}\n"
"PlotWidget{ color: rgb(35, 85, 244) !important}\n"
"QTabBar{ background: #999; color: rgb(9,9,9)} ")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setWhatsThis("")
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab1 = QtWidgets.QWidget()
        self.Tab1.setObjectName("Tab1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Tab1)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotarea = PlotWidget(self.Tab1)
        self.plotarea.setMinimumSize(QtCore.QSize(320, 0))
        self.plotarea.setStyleSheet("width: 60%; border: 1px solid #999")
        self.plotarea.setObjectName("plotarea")
        self.horizontalLayout.addWidget(self.plotarea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.decrementBtn = QtWidgets.QPushButton(self.Tab1)
        self.decrementBtn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.decrementBtn.setFont(font)
        self.decrementBtn.setObjectName("decrementBtn")
        self.horizontalLayout_3.addWidget(self.decrementBtn)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.setpullspeedLabel = QtWidgets.QLabel(self.Tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpullspeedLabel.sizePolicy().hasHeightForWidth())
        self.setpullspeedLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(30)
        self.setpullspeedLabel.setFont(font)
        self.setpullspeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setpullspeedLabel.setObjectName("setpullspeedLabel")
        self.verticalLayout_2.addWidget(self.setpullspeedLabel)
        self.label = QtWidgets.QLabel(self.Tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.incrementBtn = QtWidgets.QPushButton(self.Tab1)
        self.incrementBtn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.incrementBtn.setFont(font)
        self.incrementBtn.setObjectName("incrementBtn")
        self.horizontalLayout_3.addWidget(self.incrementBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.startBtn = QtWidgets.QPushButton(self.Tab1)
        self.startBtn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout.addWidget(self.startBtn)
        self.logdataBtn = QtWidgets.QPushButton(self.Tab1)
        self.logdataBtn.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.logdataBtn.setFont(font)
        self.logdataBtn.setObjectName("logdataBtn")
        self.verticalLayout.addWidget(self.logdataBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.Tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 30, 10, 30)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.manualDial = QtWidgets.QDial(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualDial.sizePolicy().hasHeightForWidth())
        self.manualDial.setSizePolicy(sizePolicy)
        self.manualDial.setMinimumSize(QtCore.QSize(300, 300))
        self.manualDial.setStyleSheet("")
        self.manualDial.setMinimum(0)
        self.manualDial.setMaximum(100)
        self.manualDial.setSliderPosition(50)
        self.manualDial.setNotchesVisible(True)
        self.manualDial.setObjectName("manualDial")
        self.horizontalLayout_4.addWidget(self.manualDial)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fixed_label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_label.sizePolicy().hasHeightForWidth())
        self.fixed_label.setSizePolicy(sizePolicy)
        self.fixed_label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.fixed_label.setFont(font)
        self.fixed_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fixed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fixed_label.setObjectName("fixed_label")
        self.verticalLayout_3.addWidget(self.fixed_label)
        self.currentPositionLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentPositionLabel.sizePolicy().hasHeightForWidth())
        self.currentPositionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(72)
        self.currentPositionLabel.setFont(font)
        self.currentPositionLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentPositionLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentPositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPositionLabel.setObjectName("currentPositionLabel")
        self.verticalLayout_3.addWidget(self.currentPositionLabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tom Accelerated Pull Test"))
        self.decrementBtn.setText(_translate("MainWindow", "-"))
        self.setpullspeedLabel.setText(_translate("MainWindow", "50"))
        self.label.setText(_translate("MainWindow", "In/s"))
        self.incrementBtn.setText(_translate("MainWindow", "+"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.logdataBtn.setText(_translate("MainWindow", "Log Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab1), _translate("MainWindow", "Test Mode"))
        self.fixed_label.setText(_translate("MainWindow", "Current Position (in unit)"))
        self.currentPositionLabel.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Manual Control"))

from pyqtgraph import PlotWidget
